language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - echo $LANG
  - echo $LC_ALL
  - gcc --version

script:
  - mkdir build && cd build && cmake .. && make

branches:
  only:
    - master
os:
  - linux
