language: cpp

compiler:
  - gcc

before_install:
  - gcc --version
  - git clone https://github.com/biicode/misc.git
  - pushd misc
  - sudo ./travis/cpp/gcc_update.sh --version 4.9
  - gcc --version
  - popd
  - rm -fr misc

script:
  - mkdir build && cd build && cmake .. && make

branches:
  only:
    - master
os:
  - linux
